### ISSUE TITLE
MAIL_FROM_ADDRESS and other specific for tenant

### ISSUE THREAD

**Issue by Gjonni** [stancl/tenancy-docs#104]
Hi,
I have correctly configured laravel, stancl / tenancy and other package but ...
How do I configure the values ​​in ".env", for example MAIL_FROM_ADDRESS different for each tenant?

the documentation talks about tenant config but it is not very clear

or in the past I created a file /config/mail.php in the specific folder of the tenant, so a kind of root override but now it doesn't work.
if I create the file in storage / <tenantsuffix> / <tenant_id> /config/mail.php it doesn't work,where am i wrong?

Thanks and regards,
G

**Comment by stancl** [comment]
Hey, please see the main repo to see where to ask support questions.

**Comment by Gjonni** [comment]
sorry.. where?
