### ISSUE TITLE
Add to Docs...

### ISSUE THREAD

**Issue by santiagazo** [stancl/tenancy-docs#120]
I'm not sure of all the ins and outs of the file. I am not advanced enough to really do a great job describing how to do this, but it would be GREAT to add to the documentation how to call the tenants:run command with `Artisan::call()`. It is possible! I just figured it out, but it's not well documented and certainly it's something that someone else has had to figure out. I'd love to fork this repository and add it, but I'm not sure how to do it, git is not a strong point for me. 

Anyway this is my use case if you want to use it as an example:

```
        Artisan::call('tenants:run', [
            'commandname' => "db:seed",
            '--tenants' => ["sample"],
            '--option' => ["class=SampleDatabaseSeeder"]
        ]);
```

The rough part for me was figuring out how to add the `commandname` argument as I found no documentation for it and because the `vendor/stancl/tenancy/src/Commands/Run.php` file has a kind of abstract name and because you can't just click through to it in the IDE  (`'tenants:run'` = no clicky clicky) I didn't find it until I was able to get my code close enough that an error was thrown in it and a stack trace could help me find it. 

The most difficult areas on this without documentation are:
Knowing to use the `commandname` argument
Knowing how to use the `commandname` argument (ie: NOT `--commandname`)
Knowing when to put the value in an array and when to not do it - (command name requires `string` while the options and tenants require an `array`.

So, if you feel it's warranted, I think it could be crazy helpful to others. If not, hopefully, I've put enough keywords in this post that someone else can find it. All the best and THANK YOU for such an incredible package.

**Comment by mirzazeyrek** [comment]
good catch I was also looking for this thanks for sharing!
