### ISSUE TITLE
/tenancy/assets/images/icons/manifest.json 500

### ISSUE THREAD

**Issue by dssd-nueve3** [stancl/tenancy-docs#129]
I get these errors in the console on chrome.  when accessing tenant domain.

GET https://xxx.xxx.test/tenancy/assets/images/icons/manifest.json 500
Manifest: Line: 1, column: 1, Syntax error.

**Comment by hmusman** [comment]
We are also facing same problem.

**Comment by stancl** [comment]
Not a docs issue
