### ISSUE TITLE
Redis Cache not working in scheduler commands

### ISSUE THREAD

**Issue by vinoth117** [stancl/tenancy-docs#149]
i have stored a value in redis like below
`Cache::store('redis')->put('current_date', '2022-01-01', \now()->addHours(24));`

![image](https://user-images.githubusercontent.com/97218086/148345880-539a385c-5642-45d1-86be-da778de200a0.png)

During the Artisan call, the above-stored value returns as null instead of a date.

**Comment by stancl** [comment]
Can you show the full code?

**Comment by vinoth117** [comment]
In kernel.php
![image](https://user-images.githubusercontent.com/97218086/148395915-5c286dd5-586d-41b1-8ec5-287ebea02032.png)

Run a task for a tenant.  Used to define cron jobs.
![image](https://user-images.githubusercontent.com/97218086/148395736-d093d69d-d4e2-45e5-857a-48f674629790.png)

Let me know if you need anything on this

**Comment by stancl** [comment]
That's a usage issue. You shouldn't be using the schedule like this. See the support channels on the main repo if you need help.
