### ISSUE TITLE
Should warn developers this package might cause 2 db connections per request/process

### ISSUE THREAD

**Issue by eslym** [stancl/tenancy-docs#162]
Laravel does auto open db connection when needed but it does not auto close simply because it doesnt know is the connection really no usage anymore. This behavior creates a unique problem in this package.

Let's see... when we enter the tenent's context, the database bootstrapper creates new db config and named it `tenant` and set the default db config to it, at the same time the old connection is still there and most probably already opened for fetching the tenants table and.... it stays open but most of the time like http request or queue job, that connection will not be used anymore just stay there until the end.

It still doesn't seems a problem because when the request done everything will gone and the connection will closed also.... until someone wrote tons of bad codes causing the request and queue job run for long time and there is sufficient user to cause the system hits the db connections limit. This behavior indirectly cut the db connections capacity into half.

This is not really a big deal (only for those who will study the package they used for their project rather than just install and hopes everything goes fine), an event listener for closing the central connection can solve the problem, but i think it still great to warn developers this might happens somewhere in the document.

p/s: this issue wont exists if the tenant db is hosted in different db instance

**Comment by stancl** [comment]
FYI this isn't a problem when the cached resolver is used since the central connection isn't established in the first place (unless necessary for things other than tenant identification).
