### ISSUE TITLE
Single-database tenancy Documentation

### ISSUE THREAD

**Issue by ahosker** [stancl/tenancy-docs#208]
RE: https://tenancyforlaravel.com/docs/v3/single-database-tenancy

> To use single-database tenancy, make sure you disable the DatabaseTenancyBootstrapper which is responsible for switching database connections for tenants.

How?

This is done via the Tenancy Config? Commenting out the DatabaseTenancyBootstrapper in bootstrappers

> Also make sure you have disabled the database creation jobs (CreateDatabase, MigrateDatabase, SeedDatabase ...) from listening to the TenantCreated event.

How?

This is done via the App\Providers\TenancyServiceProvider::class presumably.

No idea, still working this out for myself.

**Comment by stancl** [comment]
You comment out the bootstrapper in the tenancy config.

And yes, those jobs are disabled in the TenancyServiceProvider.
