### ISSUE TITLE
[4.x] Document `tenants:dump` command

### ISSUE THREAD

**Issue by lukinovec** [stancl/tenancy-docs#213]
I propose a documentation section for the `tenants:dump` command.

Note for @stancl: the `tenants:run` command (as well as each command using the `HasTenantOptions` trait – though this one does not use it) runs for all tenants if none are passed, but this one does not – if the tenant is not passed, the command asks for it. This looks intentional and is probably not a big deal, but I think it's worth noting since tenant**s** in `tenants:dump` indicates the command runs for multiple tenants.

EDIT: removed the "(tenant-aware)" tag

The documentation:

## **Dump** {#dump}

The `tenants:dump` command dumps the database schema of a single tenant to your application's `database/schema` directory. You can either pass the key of the tenant you want to dump the schema for in the `--tenant` option or pass the tenant key when the command asks for it.

The command runs [Laravel's `schema:dump` command](https://laravel.com/docs/9.x/migrations#squashing-migrations) for the passed tenant.

```
php artisan tenants:dump

> What tenant do you want to dump the schema for?

49670df0-1a87-11e9-b7ba-cf5353777957

Database schema dumped successfuly.
```

**Comment by stancl** [comment]
Appreciate that attention to detail. Can it ever run for multiple tenants? If not, can we modify it to run for multiple tenants?

**Comment by lukinovec** [comment]
> Can it ever run for multiple tenants?

Not with the current implementation

> If not, can we modify it to run for multiple tenants?

I think so. We could make the command use the `HasTenantOptions` trait, and instead of `$this->tenant()->run(...)`, do `$this->getTenants()->runForEach(...)`.

**Comment by stancl** [comment]
Ah actually I think the way the command works (or should work) is that it takes one tenant, dumps his schema, and uses that to create the "template" for tenant DBs. Then `migrate` should be using that.

Dumping an individual tenant's schema isn't useful for anything I believe. Could you look into the implementation to verify how this works?

**Comment by lukinovec** [comment]
> uses that to create the "template" for tenant DBs

I see, I get it now. Yeah, in that case, dumping individual tenant schemas doesn't sound useful at all. So I think the command is okay. 

I'm not sure about one more thing. At the top of the console commands page, we're saying:

"Tenant-aware commands run for all tenants by default. The commands also have the --tenants option which lets you specify IDs of the tenants for which the command will run."

This command is tenant-aware, but not like it's explained in the docs (there's just one tenant, and the HasTenantOptions trait is not used). So we'll have to either reconsider the terminology of "tenant-aware commands" or change the heading here.

**Comment by stancl** [comment]
This isn't really a tenant aware tenant because it doesn't *run things for a tenant*. It *uses a tenant* for something else.

Check if the dumped schema is correctly being used for new migrations btw, like I mentioned above. I think we should have tests for that but I don't remember 100% if these changes were added to the `migrate` command (they likely were, but want to verify it).

**Comment by lukinovec** [comment]
> it doesn't run things for a tenant

It does `$this->tenant()->run(fn () => parent::handle($connections, $dispatcher))` though. Doesn't that basically run Laravel's DumpCommand for the tenant? [Here's the code](https://github.com/archtechx/tenancy/blob/master/src/Commands/TenantDump.php#L24-L29)

> Check if the dumped schema is correctly being used for new migrations btw, like I mentioned above. I think we should have tests for that but I don't remember 100% if these changes were added to the migrate command

I'll take a look at that

**Comment by lukinovec** [comment]
'dump command works' is the only related test I found. It just tests if `tenants:dump` creates the dump file https://github.com/archtechx/tenancy/blob/master/tests/CommandsTest.php#L109

**Comment by stancl** [comment]
> Doesn't that basically run Laravel's DumpCommand for the tenant

Yes, but there's a difference in the intention. We don't want to run something for a tenant. Running something for a tenant would mean that now we want to run it for tenant 1, then we want to run it for tenant 2, etc.

But with this command, **we're not doing anything to the tenant**, we're *using* a tenant to grab his schema *for other uses*.

The *other uses* are the point of the command. So it's not *about* running something for a tenant, it's about using a tenant for something.

**Comment by stancl** [comment]
> 'dump command works' is the only related test I found

You don't have to search stuff in the codebase, just open the PR that added this.

**Comment by lukinovec** [comment]
> But with this command, we're not doing anything to the tenant, we're using a tenant to grab his schema for other uses

I see, thank you for clarifying that

> You don't have to search stuff in the codebase, just open the PR that added this.

Right. I looked at the PR, and I see that it also adds another test that checks if the `migrate` command uses the dump file passed in the `--schema-path` option. It doesn't check the thing you wrote about [here](https://github.com/stancl/tenancy-docs/issues/213#issuecomment-1269015779) (unless I misunderstood it):

> I think the way the command works (or should work) is that it takes one tenant, dumps his schema, and uses that to create the "template" for tenant DBs. Then `migrate` should be using that.

That sounds like `migrate` should use the dump automatically, is that correct? If yes, then it doesn't seem like that's tested
