### ISSUE TITLE
Caching existance of tenant database

### ISSUE THREAD

**Issue by dorep** [stancl/tenancy-docs#221]
Hello,

We have noticed, that on every new request, this query is executed:
`SELECT datname FROM pg_database WHERE datname = '$name'"`

Is it possible to cache this? It is executed in `PostgreSQLDatabaseManager->databaseExists(string $name)`.

We are already using DomainTenantResolver::$shouldCache.

Thank you very much!

Best regards, Dore

**Comment by stancl** [comment]
This is a repo for docs contributions. Use the proper support channels.
