### ISSUE TITLE
error 404 with quickstart steps

### ISSUE THREAD

**Issue by pixsolution** [stancl/tenancy-docs#239]
Hello

I followed your quickstart https://tenancyforlaravel.com/docs/v3/quickstart and in the final step I open the web in the browser it gives me an error 404, it does not show me the dump or anything, only the error 404. I have cleaned the cache and nothing, I in local using a domain 'businessname.local' as a central_domains. I followed all the steps in the doc, the tenants were created correctly in the tinker, I see the DB and it is fine, it was created and it has the data of the migrations generated as you indicate in the doc.

The only thing is the domain that instead of 'foo.localhost' I used 'localhost/foo' like this 
$tenant1->domains()->create(['domain' => 'localhost/tenantname']); 
because I want as final result "businessname.local/tenantname"

I'm using:
"php": "^8.0.2",
"laravel/framework": "^9.19",
"livewire/livewire": "^2.5",
"stancl/tenancy": "^3.6"

with Xampp in windows 11.

What can be?

Regards

**Comment by stancl** [comment]
Please use this repo only for collaborating on the documentation.
