### ISSUE TITLE
Call to undefined method Stancl\Tenancy\Database\Models\Tenant::database()

### ISSUE THREAD

**Issue by camohub** [stancl/tenancy-docs#250]
I have a command which should iterate over all tenants in centrall db and run some logic over all tenant. Code looks like this

```
    /**
     * Execute the console command.
     * @return int
     */
    public function handle()
    {
    	$tenants =  Tenant::all();

		foreach ($tenants as $tenant) {
			$tenant->run(function () {
				Log::info(User::first());
			});
		}

        return 0;
    }
```
But $tenant->run() throws me an error: Call to undefined method Stancl\Tenancy\Database\Models\Tenant::database()

Does somebody know what is going on? 
Package version is "stancl/tenancy": "^3.5"

**Comment by stancl** [comment]
Please use our [Discord](https://archte.ch/discord) for support questions.

**Comment by camohub** [comment]
This looks like a bug.

**Comment by stancl** [comment]
It isn't a bug, you just have the wrong model in your `tenancy.php` config or you're importing the wrong class in that file.
