### ISSUE TITLE
Not able to identify Controllers that in tenant route

### ISSUE THREAD

**Issue by precamp-io** [stancl/tenancy-docs#254]
After the login and redirection I get a 404 error for all my routes.
When comment them all out and I run artisan command on route list I can't seem to find any of the controllers relating to those routes. Most of these controllers are in sub folders in the controller folder and namespaces have been updated

**Comment by stancl** [comment]
Please use our support channels (such as our [Discord](https://archte.ch/discord)) for support questions, not our docs repo.
