### ISSUE TITLE
[SPONSORED DOCS] The documentation for Cashier is outdated

### ISSUE THREAD

**Issue by potsed** [stancl/tenancy-docs#276]
The sponsored docs section for Laravel Cashier is using Laravel v7

For example Laravel dropped `Cashier::ignoreMigrations()` in version 10x and we are now version 11 at time of writing.

Please provide updated docs - especially for the sponsors who pay to use them.

**Comment by stancl** [comment]
Thanks for pointing this out, will update the docs in line with the current boilerplate code.

**Comment by stancl** [comment]
Done!

**Comment by potsed** [comment]
> Done!

Thank-you
