### ISSUE TITLE
Passport per tenant example

### ISSUE THREAD

**Issue by phackwer** [stancl/tenancy-docs#77]
Hi,

I wrote this migration that will do the proper work for the passport setup for each client. Since the default connection may not be mysql, it's not worth to add this in the package, but it's ok to add this in the documentation, I think. You probably can make it better as I'm still adapting our system here to get the continuous deployment working - I still did not get too deep in the code, but in the build process only.

```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SeedOAuthCredentials extends Migration
{

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $tenant = tenancy()->getTenant();
        DB::purge('mysql');
        Config::set('database.connections.mysql.database',config('tenancy.database.prefix'.$tenant->id));
        \Illuminate\Support\Facades\Artisan::call('passport:install');
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
    }
}
```

**Comment by stancl** [comment]
I added a note about the Passport integration being incomplete. I'll let someone who uses Passport fix it.
