### ISSUE TITLE
Wrong info in doc

### ISSUE THREAD

**Issue by codexianltd** [stancl/tenancy-docs#96]
laravel-permission integration section seems to have wrong code , there is no tenancy()->hook function

**Comment by stancl** [comment]
What page do you mean? Can you send a link? 

![Screenshot_20201125_135507_com android chrome](https://user-images.githubusercontent.com/33033094/100230315-df34b180-2f25-11eb-8162-b4d16940b779.jpg)

**Comment by codexianltd** [comment]
really sorry my bad , i was 3.x but was looking at 2.x doc, btw i am wondering why $this->hasRole returning roles of a diffrent tennant but i can see $this->id is in Users is showing data from right tenant , it seems somehow spatie hasRole always returning the role from tenant db on which user is logged in , while i am ruuning it in diffrent tenant context inside tenant()->run

**Comment by stancl** [comment]
Did you apply the changes as per the docs?
